apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
#  namespace: nfs-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
  volumeName: nfs-pv